[package]
name = "somnaire-toolkit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "somnaire_toolkit"
path = "src/lib.rs"

[dependencies]
reqwest.workspace = true
reqwest-tracing.workspace = true
reqwest-middleware.workspace = true